# Generated by Django 4.2.4 on 2023-09-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('objetivo', models.TextField(max_length=500)),
                ('observaciones', models.TextField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('slug_routine', models.SlugField(max_length=200, unique='True')),
            ],
        ),
    ]
