# Generated by Django 4.2.4 on 2023-09-19 21:08

from django.db import migrations, models
import django.utils.timezone
import routine.models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routines',
            name='routine_cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='routine/', validators=[routine.models.validate_file_extension_photo]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routines',
            name='video_link',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
