# Generated by Django 4.2.4 on 2023-09-03 01:14

import ckeditor.fields
from django.db import migrations, models
import servicios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('benefits', ckeditor.fields.RichTextField(blank=True)),
                ('example_photos', models.ImageField(upload_to='photos/examples/', validators=[servicios.models.validate_file_extension_photo])),
            ],
        ),
    ]
