# Generated by Django 4.2.4 on 2023-09-29 23:33

from django.db import migrations, models
import servicios.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/examples/', validators=[servicios.models.validate_file_extension_photo])),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=250)),
            ],
        ),
    ]
