# Generated by Django 4.2.4 on 2024-02-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_carousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='example_photos',
            new_name='image',
        ),
    ]
