# Generated by Django 4.2.4 on 2024-02-20 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_rename_example_photos_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='subtitle',
            new_name='imgsubtitle',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='title',
            new_name='imgtitle',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
