# Generated by Django 4.2.4 on 2023-09-07 17:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Experience', 'Experience')], max_length=100)),
            ],
        ),
    ]
