# Generated by Django 4.2.4 on 2023-09-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_remove_experience_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
