# Generated by Django 4.2.4 on 2023-09-02 23:44

import ckeditor.fields
from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('freelance', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('descript', ckeditor.fields.RichTextField(blank=True)),
                ('instagram_link', models.URLField(blank=True, max_length=100)),
                ('telephone', models.URLField(blank=True, max_length=100)),
                ('main_photo', models.ImageField(upload_to='photos/', validators=[pages.models.validate_file_extension_photo])),
                ('cv', models.FileField(upload_to='cv/', validators=[pages.models.validate_file_extension_cv])),
            ],
        ),
    ]
