# Generated by Django 4.2.4 on 2023-09-03 16:22

from django.db import migrations, models
import django.utils.timezone
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='logo_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/', validators=[pages.models.validate_file_extension_photo]),
            preserve_default=False,
        ),
    ]
